### ISSUE TITLE
节点列表中不停下拉刷新10次以上返回主界面闪退

### ISSUE THREAD

**Issue by jafyang** [kaaass/ZerotierFix#10]
华为手机系统鸿蒙2.0，后台运行一段时间系统提醒APP后台刷新频率高，耗电异常。
节点列表中不停下拉刷新10次以上返回主界面会闪退，可能是我不规范操作导致的。
以上是我使用期间反馈的问题，不得不说这个APP很棒！谢谢！

**Comment by kaaass** [comment]
感谢支持～

1. 提示耗电量大应该是正常现象
2. 闪退问题我已经复现成功了，应该是程序 BUG，正在定位具体问题的原因

**Comment by jafyang** [comment]
> 感谢支持～
> 
> 1. 提示耗电量大应该是正常现象
> 2. 闪退问题我已经复现成功了，应该是程序 BUG，正在定位具体问题的原因



> 华为手机2.0，后台运行系统提醒APP后台发现频率异常高，耗电返回。节点中暂停显示我10次以上的主界面会闪退，可能 是 操作不规范的。我使用期间反馈问题，说这个APP了不起！谢谢！



> 谢谢支持～
> 
> 1. 提示完美的应该是正常的
> 2. 闪退问题我已经复现成功了，应该是程序BUG，正在定位具体问题的原因

顺便

**Comment by jafyang** [comment]
> 感谢支持～
> 
> 1. 提示耗电量大应该是正常现象
> 2. 闪退问题我已经复现成功了，应该是程序 BUG，正在定位具体问题的原因

顺便升级

**Comment by jafyang** [comment]
> 感谢支持～
> 
> 1. 提示耗电量大应该是正常现象
> 2. 闪退问题我已经复现成功了，应该是程序 BUG，正在定位具体问题的原因

大佬最近有更新计划吗？

**Comment by kaaass** [comment]
最近在忙毕业季，暂时没有太多精力了～可能会抽空更新一些小版本，新特性应该是没时间折腾了

**Comment by jafyang** [comment]
> 最近在忙毕业季，暂时没有太多精力了～可能会抽空更新一些小版本，新特性应该是没时间折腾了

期待新版本

**Comment by kaaass** [comment]
相关问题已经在 1.0.5_189 版本中修复
