### ISSUE TITLE
能否不接管系统VPN

### ISSUE THREAD

**Issue by lns103** [kaaass/ZerotierFix#11]
因为现在的方法无法与其它VPN软件共存，希望可以提供本地sock5或者http代理，然后用户在其它VPN软件中使用IP规则分流

**Comment by kaaass** [comment]
在可预见的未来（至少 `1.x`）我应该不会实现这个功能。理由是 Zerotier 是 L2 的 VPN，而 Socks5 是 L5 的，需要的工作量会比较大，并且官方也无意支持（zerotier/ZeroTierOne#226）。

不过不排除有现有的库支持这些操作，因此欢迎代码 PR 或者进一步的讨论。

**Comment by kaaass** [comment]
由于目前官方仍没有计划支持，且本 Issue 也长期没有进一步讨论，因此将关闭此 Issue。

当然仍旧欢迎实现本 Issue 的代码 PR 或者相关话题的进一步讨论，可以继续在此 Issue 下回复。
