### ISSUE TITLE
有使用方法么？一直入轨不了，提示moon地址格式错误，这个地址需要填写什么？

### ISSUE THREAD

**Issue by einsqing** [kaaass/ZerotierFix#12]
有使用方法么？一直入轨不了，提示moon地址格式错误，这个地址需要填写什么？

**Comment by kaaass** [comment]
两处都填写 Moon 的地址即可。Moon 文件的文件名（`XXXX.moon`）就是 Moon 的地址。

**Comment by einsqing** [comment]
建议完善下文档，我连moon文件都不知道咋生成，搞了有40分钟

**Comment by kaaass** [comment]
感谢建议，会考虑写一个上手教程
