### ISSUE TITLE
通信路径不生效

### ISSUE THREAD

**Issue by Gjorn-4389** [kaaass/ZerotierFix#13]
您好，想请问一下？我遇到了在Android端查看Windows节点，**通信路径显示的是中继**。
#4 中您所说的，空world.bin，我也导入了，在查看列表中确实看不到其他根节点，只有两个叶节点（一个Windows节点，一个network结点）和一个Moon中转节点（腾讯云服务器Moon节点）。
想请教一下，这种情况应该如何解决呢？

**Comment by kaaass** [comment]
通信路径中继并不代表通信不能建立，反过来说中继也不一定就可以变为直连。P2P 连接建立的一般条件是，两端设备至少有 1 端是 NAT1（全锥体）或两端都不是 NAT4（对称）。如果网络条件不符合，那么不管怎么操作都是没有可能建立 P2P 连接的。

不过 P2P 建立失败也可能是因为软件本身的问题。可以在同 Wifi（建议使用家庭 Wifi，否则可能有 AP 隔离） 下的情况测试下 Android 与电脑是否可以建立 P2P 连接。如果不行的话，一种常见的情况是 Moon 服务器防火墙没有放行 9993 UDP 端口，可以检查一下。

**Comment by Gjorn-4389** [comment]
感谢您的解答，我再检查一下配置是否正确！
