### ISSUE TITLE
可以更新一下版本吗

### ISSUE THREAD

**Issue by yaotthaha** [kaaass/ZerotierFix#14]
官方已经到1.8.10了。现在这个版本好像有点问题：在仅IPv4环境下，无法连接zerotier网络内的IPv6。如果可以的话可以做个action自动编译

**Comment by kaaass** [comment]
相关功能已经在 1.0.5_189 版本中实现。

P.S. 关于自动编译的 Action 我之前也想过要搞一个，但是由于目前 JNI 还是依赖于官方 Android 端编译的版本，而官方版本又只在 Google Play 发布，因此目前还是不太好实现。完成源码编译 JNI 后会考虑实现。
