### ISSUE TITLE
数据流量切换WiFi后，一直打洞失败，显示成功了，但是访问不了。

### ISSUE THREAD

**Issue by zanezha0** [kaaass/ZerotierFix#16]
数据流量切换WiFi后，一直打洞失败，显示成功了，但是访问不了。

**Comment by kaaass** [comment]
”访问不了“ 是指什么呢？无法访问到其他节点上的资源吗？

我本地暂时无法复现这个问题，请优先考虑检查配置与网络条件是否正确合适，如还有问题请提供更多的信息（如网络拓扑、配置等等）和稍微详细一些的复现步骤。

**Comment by youtehub** [comment]
最新版的zero中，我这边如果是在连接WiFi的情况下，连接私有站点的话，会提示一直在获取配置，没有办法拿到配置，然后连接失败，如图所示。使用移动网络连接的话，都是可以直接连接成功，不会出现任何问题。
![Screenshot_20220821_161044_net kaaass zerotierfix_edit_297013175268220](https://user-images.githubusercontent.com/18629921/185782203-b2753963-bc5f-4baa-8a61-b25d79e02513.jpg)

**Comment by youtehub** [comment]
已确定，在某些wifi模式下，会出现这个图示的状态，无法显示出**正确的ip**，一直**显示正在请求配置**

**Comment by kaaass** [comment]
感谢本 Issue 中的各类报告。

请求配置问题应该与 #44 有关，是网络详细界面存在一些数据同步问题。考虑到这个问题与原始 Issue 提到的问题不同，并且原始 Issue 也长期没有后续的信息，因此将关闭此 Issue。相关问题将在 #44 继续追踪。
