### ISSUE TITLE
Drawables missing

### ISSUE THREAD

**Issue by alireza787b** [kaaass/ZerotierFix#2]
Hi Thanks for the great work
I was struggling to import this project in my android studio and build my own APK. It looks like some of the drawable files such as 
baseline_link_24.xml
baseline_cloud_download_24
baseline_description_24

are missing
I manually build those drawable and it started working again... Is there a problem with the source code?

**Comment by kaaass** [comment]
Yes, it seems that they are missing accidentally. Thanks for pointing that! I'll commit them later.
