### ISSUE TITLE
安卓4.4.4闪退

### ISSUE THREAD

**Issue by XiaguangJ** [kaaass/ZerotierFix#20]
最新版1.8.9
可以安装和启动app
但点击 开关连接就闪退了
手机oppo A31 
安卓版本4.4.4

**Comment by kaaass** [comment]
我的环境暂时无法复现这个问题。由于相关信息比较少，目前我也没办法继续调查这个问题。

P.S. 如果有相关调试经验的话，可以提供下崩溃时日志供我进一步研究。不过由于目前 APP 没有内置的日志抓取工具，所以大概需要一些开发或者调试经验才能抓。

**Comment by lanyucomputer** [comment]
可以的话，麻烦也让4.2.2的老设备可以安装使用，用1.05——1.89的版本安装会提示解析包出错

![42c3111d84903a276d97886825a32bf](https://user-images.githubusercontent.com/68012194/195307159-e371264b-58d7-4db8-b314-33bffdf95fa0.jpg)
![1d93b0d0a11e9aca4aebeec1f51ae73](https://user-images.githubusercontent.com/68012194/195307389-e1b4f2f9-f328-4084-830e-91238657ec79.jpg)
安装1.4.6.5版本是可以安装成功，但是连不上后台

**Comment by lanyucomputer** [comment]
4.4.4和4.2.2的差别都有这么大吗，4.4.4能装1.89，我的4.2.2就安装不了

**Comment by lanyucomputer** [comment]
可以安装了，新的问题是，添加了
Network ID之后也是可以，但下一步打开开关的时候就闪退了，打不开

**Comment by kaaass** [comment]
@lanyucomputer 你的问题似乎与这个 issue 的无关，建议新开一个 issue。这个 issue 因为长期没有进一步的相关信息，我就先关闭了。如果 @XiaguangJ 未来提供了进一步可供分析的信息的话可以直接在此评论，我再打开此 issue。
