### ISSUE TITLE
支持老设备 Android 4.2.2

### ISSUE THREAD

**Issue by lanyucomputer** [kaaass/ZerotierFix#22]
设备是车载导航，系统 是android4.2.2,联连的是手机热点共享出来的WIFI信号，可以上网，但用zerotier后台显示也可以上线，，我现在装 的是1.4.6版本的，可以在网页控制后台看到连上了，但就是不能访问内网资源，有没有支持老设备的zerotier新版本,我也不确定是连手机热点WIFI的问题（用另一部手机安装新版的zerotier1.89连接手机热点是可以访问内网资源的），还是什么原因导致，但换新一点的版本试下，看能不能解决

**Comment by lanyucomputer** [comment]
大神请现身

**Comment by kaaass** [comment]
前段时间一直在隔离，所以一周都没怎么看。之前选择 4.4（API 19） 主要是参考了 Android 官方的系统占有率调研，在减少对开发的影响下找的最旧版本。不过目前的代码兼容 4.2.2（API 17）倒也没有问题，鉴于有使用需求我还是增加一下老版本的支持了，当然要是之后对开发有大的影响也可能会移除老版本的支持。附件是新编译的版本，可以先尝试用一下。正式发布还是等下一次更新一起了。
[app-debug.zip](https://github.com/kaaass/ZerotierFix/files/9776699/app-debug.zip)

**Comment by lanyucomputer** [comment]
> 前段时间一直在隔离，所以一周都没怎么看。之前选择 4.4（API 19） 主要是参考了 Android 官方的系统占有率调研，在减少对开发的影响下找的最旧版本。不过目前的代码兼容 4.2.2（API 17）倒也没有问题，鉴于有使用需求我还是增加一下老版本的支持了，当然要是之后对开发有大的影响也可能会移除老版本的支持。附件是新编译的版本，可以先尝试用一下。正式发布还是等下一次更新一起了。

感谢大佬无私奉献

**Comment by lanyucomputer** [comment]
> 前段时间一直在隔离，所以一周都没怎么看。之前选择 4.4（API 19） 主要是参考了 Android 官方的系统占有率调研，在减少对开发的影响下找的最旧版本。不过目前的代码兼容 4.2.2（API 17）倒也没有问题，鉴于有使用需求我还是增加一下老版本的支持了，当然要是之后对开发有大的影响也可能会移除老版本的支持。附件是新编译的版本，可以先尝试用一下。正式发布还是等下一次更新一起了。 [app-debug.zip](https://github.com/kaaass/ZerotierFix/files/9776699/app-debug.zip)

下载附近程序安装，确实可以安装了，新的问题是，添加了
Network ID之后也是可以，但下一步打开开关的时候就闪退了，打不开

**Comment by lanyucomputer** [comment]
![cec6a4dd60753de389ebec89f5b32b5](https://user-images.githubusercontent.com/68012194/196022860-71b07ec8-c056-44fe-857f-302cc3c545c0.jpg)
在android 11设备上也可以安装，但不能上线，在android4.2.2上安装可以安装，填好network id 后闪退

**Comment by lanyucomputer** [comment]
android 11 可以上线，但要在后台手动添加客户端的ID，还有上线的反应好像比较慢，如果不手动添加，后台一直不会出来让打勾的验证，android4.2.2 设备还是闪退

**Comment by kaaass** [comment]
> Network ID之后也是可以，但下一步打开开关的时候就闪退了，打不开

抱歉，这个确实是我没有进行测试造成的，当时以为能编译能打开就 OK 了。我检查下问题，是 Native 库与老版本系统不兼容造成的。遗憾的是，要解决这个问题就必须要先解决 Native 库的编译问题，而这个问题的解决此前还没有确定的计划。也就是说 Android 4.2.2（API 17）的支持至少要到这个问题解决后才能再考虑了，可能会是在 v1.1 吧。不过 Native 库的编译问题还能解决 #19，我最近可能会研究下相关的操作。

**Comment by lanyucomputer** [comment]
> > Network ID之后也是可以，但下一步打开开关的时候就闪退了，打不开
> 
> 抱歉，这个确实是我没有进行测试造成的，当时以为能编译能打开就 OK 了。我检查下问题，是 Native 库与老版本系统不兼容造成的。遗憾的是，要解决这个问题就必须要先解决 Native 库的编译问题，而这个问题的解决此前还没有确定的计划。也就是说 Android 4.2.2（API 17）的支持至少要到这个问题解决后才能再考虑了，可能会是在 v1.1 吧。不过 Native 库的编译问题还能解决 #19，我最近可能会研究下相关的操作。

那就有劳大佬了

**Comment by kaaass** [comment]
目前 #32 的问题已经得到解决，因此更旧版本的 Android 设备也可以进行支持了。不过考虑到 API < 19（Android 4.4）之前的设备数量较少，另一方面旧 API 也会增大维护成本，因此目前决定主线分支及正常的版本发布依旧以 Android 4.4 作为最小支持版本，但同时单独开一个分支来维护适用于老 Android 版本的 APP。这个分支的维护、发布都会比主分支更慢一些，不过因为已经启用了 Workflow，因此可以随时获取旧分支当前最新版本的构建结果（nightly build）。

目前最新的版本可以在此处下载：https://github.com/kaaass/ZerotierFix/actions/runs/5516586362。由于问题已解决，因此本 Issue 将关闭。但如有问题可继续回复。
