### ISSUE TITLE
Does ethernet bridging work?

### ISSUE THREAD

**Issue by arminask** [kaaass/ZerotierFix#23]
Does ethernet bridging work with this app?

**Comment by lanyucomputer** [comment]
i think so ,it works well

**Comment by kaaass** [comment]
Not at the moment. Zerotier Fix receives ethernet frames but will only process those carries IPv4, IPv6, or ARP payload. But please note that the Android system's VpnService only provides TUN ability, which means it works on L3. So ethernet bridging might be very hard to be implemented and thus not scheduled for Zerotier Fix.
