### ISSUE TITLE
手机移动网络下，用自建moon节点，无法上线。

### ISSUE THREAD

**Issue by lengyun123456789** [kaaass/ZerotierFix#24]
1.0.5_189.apk ，在wifi下面用自建moon服务节点没有问题；切换到5G网络，不能上线，退出重启也不能上线，一直显示已断开。设备是小米k50，移动网络使用的是电信5G。

**Comment by kaaass** [comment]
检查下节点列表中你的 MOON 节点的状态，是否是 “中继”？

**Comment by lengyun123456789** [comment]
> 检查下节点列表中你的 MOON 节点的状态，是否是 “中继”？

谢谢，应该没问题了。
