### ISSUE TITLE
通过 Zt 网络进行远程 ADB 调试时 APP 占用大量内存并卡死 / The APP hangs and consumes excessive memory during remote ADB debugging via Zerotier

### ISSUE THREAD

**Issue by ChenDoXiu** [kaaass/ZerotierFix#25]
效果复现
1.使用zerotier和远程pc建立局域网
2.远程pc打开android studio，手机打开无线调试
3.远程pc的android studio使用 adb connect 局域网ip:port 连接手机

此时logcat中出现大量日志，手机zerotier内存占用飙升，直至卡死

目测是项目中的Log.d的问题，当产生流量时会打印debug信息，然后信息经过vpn转发后日志被层层放大，最后导致卡死

**Comment by kaaass** [comment]
感谢报告，你的分析看起来非常合理！不过我近日稍微有点忙，可能没太多时间测试。我尽量抽空日间编译一个流量不 log 的版本，可以的话麻烦你看下是否解决问题了。

**Comment by kaaass** [comment]
本 Issue 已经得到修复，预计下个版本更新将包含此修复。需要注意的是，目前仅当编译时使用 Release profile 时才不会输出网络包相关的日志，因此 master 分支 Workflow 中的 nightly build 仍会存在此问题（Workflow 是 Debug 编译），仅当版本发布时才会使用 Release profile。下一版本发布前可以用此包进行该修复的测试：[app-release.zip](https://github.com/kaaass/ZerotierFix/files/12012019/app-release.zip)。

由于问题已被修复，因此本 Issue 将关闭。若仍有问题欢迎继续回复。
