### ISSUE TITLE
突然间使用数据流量连接失败

### ISSUE THREAD

**Issue by Passerby1011** [kaaass/ZerotierFix#28]
一直提示获取配置中

**Comment by kaaass** [comment]
请检查节点列表中与 Planet 服务器的连接情况，或者添加自建 Moon。近日官方 Planet 在特定地区的连接情况似乎十分不稳定。

**Comment by Passerby1011** [comment]
自建的路由连上了延迟大概在30左右，手机和平板无论怎么连接都连不上显示获取配置中，planet服务器看到设备了也分配了ip

**Comment by Passerby1011** [comment]
自建的，但是路由连上了，延迟大概在30左右，手机和平板无论怎么连接都连不上显示获取配置中，planet服务器看到设备了也分配了ip

**Comment by kaaass** [comment]
自建的是指 Moon 吗？可以检查 Moon 配置是否显示已缓存。

此外，请检查 **APP 中** 节点列表中与 Planet 服务器的连接情况，不是 Web Controller 中的连接情况。

**Comment by Passerby1011** [comment]
自建的moon和伪planet
https://github.com/Jonnyan404/zerotier-planet
https://github.com/jonnyan404/docker-zerotier-moon项目地址
![Screenshot_20221106_193535](https://user-images.githubusercontent.com/63802758/200168404-d8647647-546b-4e4c-b53e-5042e2120b7c.jpg)
![Screenshot_20221106_193508](https://user-images.githubusercontent.com/63802758/200168407-9f8208cc-4b59-4412-a75f-e82769077939.jpg)

**Comment by kaaass** [comment]
请检查 APP 首页的右上角的“结点列表”，查看与 Planet 服务器和 Moon 服务器的连接情况。

**Comment by Passerby1011** [comment]
空的

**Comment by Passerby1011** [comment]
无连接

**Comment by kaaass** [comment]
是否有设置过自定义 Planet？如果有的话则建议先在设置里停用。

**Comment by Passerby1011** [comment]
没有用过自定义，同样的东西，一个星期前是正常使用的

**Comment by Passerby1011** [comment]
今天节点列表里又有节点了。
![Screenshot_20221107_124846_net kaaass zerotierfix](https://user-images.githubusercontent.com/63802758/200228963-61266513-a2b8-4a36-8b90-49bc0cc9f7f3.jpg)
![Screenshot_20221107_124843_net kaaass zerotierfix](https://user-images.githubusercontent.com/63802758/200228969-e4f23b10-1795-4cd0-942f-6a62b104012c.jpg)

**Comment by Passerby1011** [comment]
但依旧是“正在请求配置”
