### ISSUE TITLE
Does ZeroTierFix support DNS configuration override?

### ISSUE THREAD

**Issue by jerry-yuan** [kaaass/ZerotierFix#29]
I have configured a DNS configuration override on zerotier.com:
![Screenshot_20221108-102714.jpg](https://user-images.githubusercontent.com/13380647/200460072-131bd11f-dba5-4f8f-b98b-fdf524f1b067.jpg)

I have tested in official zerotier app with zerotier version 1.8.9-1, it can redirect DNS queries on my phone to my dns server and my private hostnames (like openwrt.lan) can be resolved. But on ZeroTierFix, I found that these hostname cannot be resolved. 
![Screenshot_20221108-103437.jpg](https://user-images.githubusercontent.com/13380647/200461140-00b6cbce-3c70-4b75-a325-638e6d660426.jpg)
I tried to resolve hostnames in Termux by nslookup with specified DNS server, and the  result is that I can get the right IPs.
![Screenshot_20221108-103416.jpg](https://user-images.githubusercontent.com/13380647/200461162-0d102d76-8e51-4978-af47-a53783a6a00a.jpg)

I want to know if there is any possible to add this feature?

**Comment by kaaass** [comment]
That's strange... Zerotier Fix is expected to act the same as the official App in DNS behavior (since we merely extend but do not modify).

Since you managed to do a DNS query through `nslookup`, maybe this issue is caused by misconfiguration. While joining the network, Zerotier Fix will ask you to choose the DNS type. Please be sure to choose the "Network DNS" (switch to the middle tab).

**Comment by jerry-yuan** [comment]
> That's strange... Zerotier Fix is expected to act the same as the official App in DNS behavior (since we merely extend but do not modify).
> 
> Since you managed to do a DNS query through `nslookup`, maybe this issue is caused by misconfiguration. While joining the network, Zerotier Fix will ask you to choose the DNS type. Please be sure to choose the "Network DNS" (switch to the middle tab).

Thanks for your reply. I found DNS configuration by rejoin the network! It's such a wired design that the official app cannot change the DNS type after joined a network. Thanks a lot again!
