### ISSUE TITLE
Cannnot resolve dependencies

### ISSUE THREAD

**Issue by alireza787b** [kaaass/ZerotierFix#3]
Hi sir
Debug version build is ok.
I tried to build the release version. I get the following missing dependencies error: Is there sth wrong with my configuration?

Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all files for configuration ':app:lintClassPath'.
   > Could not find com.android.tools.lint:lint-gradle:27.2.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.2.1/lint-gradle-27.2.1.pom
       - https://jcenter.bintray.com/com/android/tools/lint/lint-gradle/27.2.1/lint-gradle-27.2.1.pom
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

-------------------------------------------------------

I also tried to build in MacOS in debug mode. Again I got another missing dependency error:

Execution failed for task ':app:processDebugResources'.
> Could not isolate parameters com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Parameters_Decorated@4d854b62 of artifact transform AarResourcesCompilerTransform
   > Could not isolate value com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Parameters_Decorated@4d854b62 of type AarResourcesCompilerTransform.Parameters
      > Could not resolve all files for configuration ':app:detachedConfiguration1'.
         > Could not find aapt2-4.2.1-7147631-osx.jar (com.android.tools.build:aapt2:4.2.1-7147631).
           Searched in the following locations:
               https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/4.2.1-7147631/aapt2-4.2.1-7147631-osx.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by kaaass** [comment]
I tried under Gradle 6.5 and AS 4.1.1 but not able to reproduce this issue. According to your Gradle log, I suspect that it might be a network issue. Could you try to run `clean` task and build in another network condition? Or validate whether you could access https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.2.1/lint-gradle-27.2.1.pom .
