### ISSUE TITLE
替换预编译 JNI 库为 ZT 源码编译 / Replace pre-built JNI library

### ISSUE THREAD

**Issue by kaaass** [kaaass/ZerotierFix#32]
## 描述

目前 Zerotier Fix 仍然在仓库中使用预编译的 JNI 库。这种分发方式使得 Zerotier Fix 目前无法做到完全的源码编译，因而降低了项目的透明度。此外，目前 Zerotier Fix 源码库中仍包含部分 ZT SDK 源码。这可能会造成 SDK 与 JNI 库对应的版本不一致，并且还有可能造成潜在的 LICENSE 问题。因此，本 Feature 旨在实现如下内容：

1. 替换预编译的 JNI 库为从 ZT 源码编译
2. 从目前仓库托管的源码树中移除 ZT SDK 相关的源码，转而在编译前从 Zerotier 官方仓库中获取对应版本的代码

## 相关 Issue

- Windows 下编译 JNI 的脚本 #31
- 更新内核版本，实现此 Feature 后应能一并解决 #19

**Comment by maryjeck** [comment]
老大，yyds

**Comment by sffxzzp** [comment]
参考 #31，用 Github Actions 搞了个自动编译 apk，目前可以打包 1.10.3。
地址见：[https://github.com/sffxzzp/ZerotierFix-Build](https://github.com/sffxzzp/ZerotierFix-Build)

根据 [ZeroTierOne#77c7f9](https://github.com/zerotier/ZeroTierOne/commit/77c7f9133f1530580978e676bf56b18126a5ccc6)，Zerotier Core 应该是已经切换到 CMake 来编译了。
但目前尝试了几次，不太会弄，所以还是用的 ndk-build。

编译的时候出的几个问题，我的解决方法也很糙，供作者参考，希望能有帮助。

**Comment by kaaass** [comment]
感谢 @sffxzzp 提供的参考～我看看具体要怎么引入更好

**Comment by kaaass** [comment]
本 Issue 已在 #55 中实现，预计在下个更新中发布。
