### ISSUE TITLE
替换了planet和xxx.moon后未能连接上网络

### ISSUE THREAD

**Issue by Jasper-zh** [kaaass/ZerotierFix#33]
目前是我的电脑成功连上私有化部署的网络，但手机未能连上去

**Comment by kaaass** [comment]
请提供更详细的信息，可能包括但不限于：

1. 你做了什么操作
2. 你进行了什么测试使你确信是 Zerotier Fix 导致无法连接的

因为此处是 Zerotier Fix 源代码的 Github Issue，主要是用于追踪 Zerotier Fix 的程序错误、新功能等等的，我没有太多精力也没能力回答其他 Zerotier 有关问题。因此和一般的交流群、论坛不同，在你打开新 Issue 的时候希望你已经进行了一些测试，比如用 ping 进行检查。并且在问题描述中，给出你的测试环境、网络设置、问题现象。否则，建议在交流群、论坛等渠道进行提问，那里应该能更快的解决你的问题。

**Comment by kaaass** [comment]
由于长时间未收到详细内容相关的回复，因此关闭此 issue
