### ISSUE TITLE
安卓端与安卓端无法互通，安卓与PC端互通

### ISSUE THREAD

**Issue by CongAn** [kaaass/ZerotierFix#34]
#### 软件和设备的版本：
* zerotier-plant的服务器版本：v1.8.4，操作系统版本：Ubuntu 22.04
* ZeroTier One PC客户端版本：v1.10.2，操作系统版本：Windows 11、Windows Server 2019
* ZerotierFix 安卓客户端版本：v1.0.5_189，操作系统版本：Android 11 （MIUI 13）、Android 12 （Origin 2）

#### 通讯情况：
* 安卓->PC ✔
* PC->安卓 ✔
* 安卓->PC ✔
* 安卓->安卓 ❌

**Comment by CongAn** [comment]
> 可否详细描述下你是如何检查通讯情况的呢？

通过`ping`命令，安卓`ping`PC，PC`ping`安卓检查通信情况。
安卓手机安装命令行工具Termius等，可以使用`ping`命令。

#### 其他内容补充：
##### 环境一：
* 网络位置为家（移动宽带）和公司（企业电信宽带）。
* Windows 11 和 Android 12 （Origin 2） 设备在公司，Android 11 （MIUI 13 ）和 Windows Server 2019 设备在家。
* 即不同设备和网络地点进行两两互`ping`测试。
* 查看ZerotierFix客户端结点列表，仅有根结点和PC结点显示。
* PC->安卓 ✔
* 安卓->PC ✔
* 安卓->安卓 ❌

##### 环境二：
* 网络位置为家。
*  Windows 11 、 Android 12 （Origin 2）、Android 11 （MIUI 13 ） 设备均在家。
* PC->安卓 ✔
* 安卓->PC 待测试
* 安卓->安卓 待测试

**Comment by kaaass** [comment]
我暂时无法在 VM 与实机中复现这个现象。能否检查下 `ping` 之后结点列表的状态呢？正常的话，此时结点列表中应该会显示另一台 Android 的结点。

**Comment by CongAn** [comment]
现在有新的问题，经过多设备测试。
在同一局域网下，PC设备访问安卓手机设备网络波动非常大，而安卓手机访问PC设备网络波动则相对稳定，并且相比之下访问安卓手机设备延迟要高出10倍。

#### PC设备访问安卓手机设备
```
ping 10.174.24.70 -n 20
正在 Ping 10.174.24.70 具有 32 字节的数据:
来自 10.174.24.70 的回复: 字节=32 时间=641ms TTL=64
来自 10.174.24.70 的回复: 字节=32 时间=337ms TTL=64
来自 10.174.24.70 的回复: 字节=32 时间=670ms TTL=64
来自 10.174.24.70 的回复: 字节=32 时间=166ms TTL=64
来自 10.174.24.70 的回复: 字节=32 时间=121ms TTL=64
来自 10.174.24.70 的回复: 字节=32 时间=605ms TTL=64
来自 10.174.24.70 的回复: 字节=32 时间=10ms TTL=64
来自 10.174.24.70 的回复: 字节=32 时间=15ms TTL=64
来自 10.174.24.70 的回复: 字节=32 时间=54ms TTL=64
来自 10.174.24.70 的回复: 字节=32 时间=81ms TTL=64
来自 10.174.24.70 的回复: 字节=32 时间=100ms TTL=64
来自 10.174.24.70 的回复: 字节=32 时间=111ms TTL=64
来自 10.174.24.70 的回复: 字节=32 时间=94ms TTL=64
来自 10.174.24.70 的回复: 字节=32 时间=47ms TTL=64

10.174.24.70 的 Ping 统计信息:
    数据包: 已发送 = 14，已接收 = 14，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 10ms，最长 = 670ms，平均 = 218ms
```


#### 安卓手机访问PC设备
```
ping 10.174.24.49
PING 10.174.24.49 (10.174.24.49) 56(84) bytes of data.
64 bytes from 10.174.24.49: icmp_seq=1 ttl=128 time=15.0 ms 
64 bytes from 10.174.24.49: icmp_seq=2 ttl=128 time=35.8 ms
64 bytes from 10.174.24.49: icmp_seq=3 ttl=128 time=25.1 ms
64 bytes from 10.174.24.49: icmp_seq=4 ttl=128 time=23.7 ms
64 bytes from 10.174.24.49: icmp_seq=5 ttl=128 time=23.9 ms
64 bytes from 10.174.24.49: icmp_seq=6 ttl=128 time=39.0 ms
64 bytes from 10.174.24.49: icmp_seq=7 ttl=128 time=27.3 ms
64 bytes from 10.174.24.49: icmp_seq=8 ttl=128 time=28.6 ms
64 bytes from 10.174.24.49: icmp_seq=9 ttl=128 time=35.0 ms
64 bytes from 10.174.24.49: icmp_seq=10 ttl=128 time=22.1 ms
--- 10.174.24.49 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9019ms
rtt min/avg/max/mdev = 15.028/27.595/39.044/6.911 ms
```

**Comment by kaaass** [comment]
> PC设备访问安卓手机设备网络波动非常大

建议测试下直接 `ping` 手机在局域网中的 IP 地址，检查网络波动是否受到如 WiFi 或者其他非 Zerotier 因素等的影响。

**Comment by CongAn** [comment]
> 建议测试下直接 `ping` 手机在局域网中的 IP 地址，检查网络波动是否受到如 WiFi 或者其他非 Zerotier 因素等的影响。

经过测试局域网，你是对的。
不使用Zerotier，网络波动依旧很大。
感谢回复，我可能脑子瓦特了。

不过，终于搭建建立好了公司和家的组网，并部署了旁路由转发。
现在在安卓手机上，可以直接使用原有局域网IP访问公司或家了，简直完美。🎇🎇🎇
