### ISSUE TITLE
建议开发安卓盒子TV版

### ISSUE THREAD

**Issue by tonmy007** [kaaass/ZerotierFix#35]
大佬可否开发个安卓电视端TV版的Zerotier，实现用遥控器操作

**Comment by kaaass** [comment]
暂时没想到 TV 版应用的必要性…… 加上我也没有相关设备做测试，因此可预见的未来内应该不会专门推出 TV 版本。不过，如果现有的应用如果在 TV 端可以正常使用的话，实现一些操作上的改善是可以考虑的。
