### ISSUE TITLE
使用教程

### ISSUE THREAD

**Issue by planet618** [kaaass/ZerotierFix#36]
请问下有使用教程吗，为什么我看描述里看不懂要做什么，我在手机上也找不到关于zerotier安装路径和文件夹。（本意是想替换planet实现连接自建planet，但是找不到文件路径和文件夹）

**Comment by kaaass** [comment]
你可以在右上角的设置中选择 Planet 文件，或填写可以下载 Planet 文件的 URL。

**Comment by planet618** [comment]
大佬啊。我佩服
