### ISSUE TITLE
官方更新到1.10.3了

### ISSUE THREAD

**Issue by qzwl** [kaaass/ZerotierFix#37]
希望大大能百忙之中更新。

**Comment by wuc656** [comment]
+1 希望能更新

**Comment by leezn** [comment]
+1，现在1.10.5了

**Comment by Laowang2018** [comment]
我发现android连不上moon了， linux还可以。

**Comment by kaaass** [comment]
由于内容类似，将在 #19 track 相关更新，请移步至此讨论

**Comment by kaaass** [comment]
目前已经发布了更新至 1.10.6  核心的 ALPHA 版本 [1.0.6_011006_alpha](https://github.com/kaaass/ZerotierFix/releases/tag/1.0.6_011006_alpha)。但是由于此次更新涉及代码变动较大，很可能引入各种未知 BUG，因此暂时发布了 ALPHA 版本，**请各位务必谨慎更新**。目前短暂的测试中暂时未发现明显的 BUG，不过还要等待我再测试一段时候后再发布正式的 1.0.6_011006 版本。

如果各位在使用 ALPHA 版本时发现问题，欢迎另开 Issue 或者在 Discussion 中进行反馈。
