### ISSUE TITLE
新人问题

### ISSUE THREAD

**Issue by DanielFok99** [kaaass/ZerotierFix#39]
Hi，我有一个小白问题想请教，请问[libzt](https://github.com/zerotier/libzt)和ZerotierFix里的JNI wrapper是什么关系？我能不能使用libzt来直接connect到Zerotier呢？谢谢你们。

**Comment by kaaass** [comment]
libzt 是 Zt 官方给应用开发者提供的一个用 Zerotier 做的 Socket 实现。不能用来做正常的客户端，是用来给开发者快速建立 P2P 网络的，比如你要写一个聊天软件就可以用。

**Comment by DanielFok99** [comment]
好的明白，谢谢你的回复
