### ISSUE TITLE
权限问题可能导致本地导入Planet文件失败

### ISSUE THREAD

**Issue by Y-pandaman** [kaaass/ZerotierFix#4]
您好，我在安卓上装了zerotierFix，添加网络成功了，也有ip，在入轨设置里导入moon节点，moon地址填的是moon的10位数的id号，完成之后显示配置文件已缓存，同时，把“通过zerotier路由”打钩了，但是用电脑ping手机的时候延迟有600多毫秒，感觉是没连接moon节点，请问您知道这是哪里出了问题吗？

**Comment by kaaass** [comment]
在首页右上角点击应该可以看到一个“结点列表”，你看看里面是否有你添加的 Moon 节点。如果有的话，检查下通信路径是什么。

**Comment by Y-pandaman** [comment]
显示 类型为moon中转，延迟30ms，通信路径为布置moon节点的阿里云服务器ip

**Comment by kaaass** [comment]
> 显示 类型为moon中转，延迟30ms，通信路径为布置moon节点的阿里云服务器ip

那连接 Moon 是没有出现问题的。你可以检查下电脑端的节点 ID（应该也是10位），然后在节点列表中找到对应的设备，看看它的通信路径是什么。假如是中继，那这样的 Ping 值是很有可能的，持续 Ping 的话应该也能看到波动。

**Comment by Y-pandaman** [comment]
通信路径显示的是中继

**Comment by Y-pandaman** [comment]
用zip文件和解压后的bin文件，导入显示文件格式错误

**Comment by kaaass** [comment]
> 用zip文件和解压后的bin文件，导入显示文件格式错误

你是在 **设置-启用自定义 Planet** 导入的吗

**Comment by Y-pandaman** [comment]
是的

**Comment by Y-pandaman** [comment]
没有损坏，校验值跟你这一样，选择bin文件，显示无法复制planet文件

**Comment by kaaass** [comment]
感觉是禁止了App的文件读写权限……

那试试 URL 导入吧：http://clould-cdn-qiniu-01.kaaass.net/storage/2021/11/30/OuoroMAw_world.bin

**Comment by Y-pandaman** [comment]
提示  无法下载planet文件

**Comment by kaaass** [comment]
试试在应用管理器里清除下缓存文件？

**Comment by Y-pandaman** [comment]
还是无法下载

**Comment by kaaass** [comment]
🥲 添加文件可能是一个 BUG，如果可以的话可以尝试用 LogcatExtreme 之类的程序抓取一下错误日志，或者尝试重装程序

**Comment by Y-pandaman** [comment]
重装了1.0.3版本，还是不行

**Comment by i-sunshine** [comment]
针对该问题我刚开始也碰到了，特意登陆上来说明下
目前我这边已解决，该app可以正常使用，谢谢kaaas大佬，过程记录如下：
1、远程的下载地址无效，也是下载不了；
2、下载压缩包，本地导入，也是导入不了，后台查app权限好像没有申请权限项目，改不了（安卓11）；
3、网上随便找个临时文件服务的，上次解压后文件，再下载获取到直链；
4、粘贴到app内，文件导入成功；
5、moon服务器无法使用，查了下原来是腾讯云清凉防火墙的udp 9993端口忘记开了，添加后，刷新ok；

以上问题顺利解决，使用moon后访问unraid内的群晖的moment，相当的丝滑。

**Comment by kaaass** [comment]
@i-sunshine 感谢报告，看起来是权限申请的 BUG

**Comment by Lixuhuilll** [comment]
我是最新的1.0.5版本，moon节点已缓存，但是节点列表显示延迟-1ms，显然没有工作，ping其他设备的延迟高达400+ms

**Comment by kaaass** [comment]
@Lixuhuilll 请检查 Moon 在节点列表中的状态。如果是 “中继” 则说明 Moon 配置有误；如果显示的是其他信息，那建议优先考虑网络问题。可以尝试在同网络环境下开热点后用电脑客户端连接查看延迟。

P.S. 本 issue 实际上已经不再追踪标题中这个宽泛的问题。因此如果要进一步回复请新打开一个 issue。

**Comment by WesleyWu** [comment]
从文件导入提示 "Planet 文件格式错误"
从URL导入提示 "无法下载 Planet 文件"

url是确认可以用手机浏览器下载的。Planet文件（二进制格式）也确认是可以使用的（覆盖linux/mac上的planet文件可工作）

版本：最新 release 版本以及 alpha 版本都试过了。

**Comment by kaaass** [comment]
@WesleyWu 请问系统具体是哪个 ROM，对应 Android 是什么版本呢？

**Comment by WesleyWu** [comment]
> 

Vivo Origin OS最新版，Android 13

**Comment by kaaass** [comment]
本 Issue 的问题已经修复，预计下个版本将包含此修复。在版本发布前，可以通过 [nightly build](https://github.com/kaaass/ZerotierFix/actions/runs/5518296206) 对相关功能进行测试。

目前我手边的 Android 设备已经没有此 Issue 的相关问题了。不过本 Issue 仍将保持打开一段时间，欢迎各位在不同设备/系统上进行测试～

**Comment by captainbanana233** [comment]
你好，在我这里这个问题依然存在，节点列表显示通信路径为中继，延迟-1ms，通过ping发现有500ms左右，应该是没有连接上，我的安卓版本是13，小米12x，MIUI14.0.9

**Comment by kaaass** [comment]
@captainbanana233 根据你的描述，你目前遇到的问题是：目标节点没有和你的手机成功建立 p2p 连接。这个问题存在非常多的可能，目前的描述中没有办法确定具体问题：

- 官方 Planet 无法连接
- 官方 Planet 连接，但是无法通过官方 Planet 与目标节点建立 p2p 连接
- 自建 Planet/Moon 服务器无法连接
- 自建 Planet/Moon 服务器成功连接，但是网络条件本身就无法建立 p2p 连接（例如双方都是移动数据上网就可能出现此问题） 

如果你自建了 Planet/Moon，可以先尝试在较为稳定的网络环境（例如家宽）下测试 Planet/Moon 是否已经正常工作了。

P.S. 这个 Issue 目前只用来追踪 Planet 文件在通过 URL 或者本地文件导入的时候发生错误的问题了。我将关闭这个 Issue，如果仍有问题的话可以另开一个新的 Issue。
