### ISSUE TITLE
节点列表的通信路径显示错误？

### ISSUE THREAD

**Issue by masx200** [kaaass/ZerotierFix#41]
节点列表的通信路径显示错误？

多一个斜杠？而且ipv6显示也不太正常？

还有，这个延迟-1ms就是断线的意思吧？应该有正确的显示才对。
而且显示延迟有数字的也不一定真的在线？
```
[地址]:端口
```
![IMG_20230326_064239.jpg](https://user-images.githubusercontent.com/34191203/227745748-b2a74a45-e851-4692-9b7a-5939c200198c.jpg)

**Comment by kaaass** [comment]
> 多一个斜杠？而且ipv6显示也不太正常？

这个是 Android SDK 的 `InetAddress` 实现的表示方式，横杠前是 Host 名。V6 的话，因为没有用省略所以歧义上应该还好？不过的确不是标准的 `[]:xxxx` 形式。

> 还有，这个延迟-1ms就是断线的意思吧？应该有正确的显示才对。
> 而且显示延迟有数字的也不一定真的在线？

这些都是和 `zerotier-cli peers` 的输出保持一致的。另外有延迟的话我个人认为基本可以认为节点在线，反倒是 Web Controller 里面看到的在线状态是不准确的，那个是单独有一个分布式网络维护的。

**Comment by kaaass** [comment]
本 Issue 中的问题已经得到修复，预计该修复将包含在下个版本更新中。
