### ISSUE TITLE
请教下，手机和电脑都连接成功了，为啥ip无法访问

### ISSUE THREAD

**Issue by cctyl** [kaaass/ZerotierFix#45]
大佬你好，我的安卓手机和pc，都已经加入了 network。此时手机通过分配的内外ip去访问pc的nginx，发现无法访问。
手机端ping pc 的内外地址，以及pc ping 手机的内网地址，都不通。
但是手机上显示连接正常。是什么原因呢？
![截图](https://user-images.githubusercontent.com/34262992/229138609-69b6d24d-6095-42a9-9858-a0ed37bec2fa.png)
![截图_20230331215208](https://user-images.githubusercontent.com/34262992/229139117-6857c337-bf31-4540-9aba-8d1d5e23fb50.jpg)

**Comment by mirthfulLee** [comment]
根据个人经验提供几个排查建议哈. 
1. 连接同一个wifi
2. 尝试使用wifi分配的局域网ip测试ping和nginx服务, 如果无法成功, 那应该是防火墙;
3. 尝试在同一wifi下使用zerotier的虚拟ip测试ping和nginx服务, 如果失败, 检查zerotier的配置;
4. 如果上述两个情况都能成功, 但是使用不同wifi无法成功, 则应该是zerotier打洞失败(原因包括但不限于两个网络不属于同一运营商, 网络跨度较大), 可以通过添加moon服务器进行转发(具体方法可以自行搜索教程)

**Comment by kaaass** [comment]
GitHub 的 Issue 通常是用于交流、跟踪程序本身的 BUG 的。对于网络连接不通的问题，因为网络配置的复杂情况，在经过一定的排查之前是难以判断这是一个程序 BUG 还是配置的问题。建议参考 @mirthfulLee 的方式进行初步排查，并补充更详细的测试结果。

**Comment by kaaass** [comment]
由于本 Issue 长期无进一步讨论或问题相关的信息补充，故关闭此 Issue。若有后续信息补充仍欢迎继续回复。
