### ISSUE TITLE
1.10.x  alpha 版小米 11 pro 机型 (MIUI 12.5) 无法连接

### ISSUE THREAD

**Issue by brdctrai** [kaaass/ZerotierFix#46]
小米11pro应用最新alpha版状态是已断开，无法连接,用ZeroTierOne1.10.apk是正常使用。在红米k20 MIUI版本12.5.2都可正常使用。
小米11pro MIUI版本是miui 12.5.20.
![YHIWHG%PNA%G)QZ{M1C(MZX](https://user-images.githubusercontent.com/117452908/234232079-acebc378-3900-4421-86c8-1015ad0761be.jpg)

**Comment by brdctrai** [comment]
无论在wifi和移动网络都无法连接。
![U{}PN63IGW 897OL }GZZ9T](https://user-images.githubusercontent.com/117452908/234236239-dc255d16-03d8-4d09-85c1-53c572449a61.jpg)

**Comment by kaaass** [comment]
我好像没太懂，是同 MIUI 版本但是型号不同的两部机器，其中小米 11 PRO 无法连接但是红米 k20 可以连接？

**Comment by brdctrai** [comment]
小米11pro用ZeroTierOne1.10.apk是正常使用

**Comment by kaaass** [comment]
好的，感谢报告！

目前我找了一圈，只找到一台小米 10s 的 MIUI 14 设备，测试可以正常连接。但是因为机型和系统版本都不一样，所以目前只能大致确定是特殊机型/特殊系统版本的问题。不过由于目前我没有这个型号的机器，也暂时不能复现所以也没法做什么调试了。本 Issue 就先保持这个状态看看还有没有其他类似机型的报告吧。建议 @brdctrai 也可以尝试下其他网络环境是否能连接，或者有什么特殊条件与该问题相关，比如安装了什么 APP 有功能冲突。

**Comment by xzl0326** [comment]
你这个bug好像和我之前那个差不多。你试试先开一个VPN应用连接再切回zerotierfix再启动

**Comment by Aes64X** [comment]
额。。。这个1.10.x alpha 确实是有些问题，在我的三桑A53上使用，他不会申请任何权限，不申请VPN权限，也不联网，打开允许移动网络使用，载流量监测里面甚至看不到这个版本使用任何流量。WLAN下也不进行任何连接。
但在使用1.0.5_189时是会正常申请VPN权限，通知，联网也正常动作。
Android  13

**Comment by kaaass** [comment]
@Aes64X 感谢报告！这个似乎是一个新的问题，不知道是否介意开个 issue 然后详细的说明下情况？不过 VPN 权限的话，如果旧版本有授权新版本应该不会再次请求。

**Comment by xzl0326** [comment]
> @Aes64X 感谢报告！这个似乎是一个新的问题，不知道是否介意开个 issue 然后详细的说明下情况？不过 VPN 权限的话，如果旧版本有授权新版本应该不会再次请求。

对，我也发现了。如果全新安装的话就不会申请VPN权限。

**Comment by kaaass** [comment]
新版本 1.0.7_011006_alpha 目前包含了 #48 提及的问题，可否麻烦 @brdctrai 再试试是否仍存在无法连接的问题？

**Comment by xzl0326** [comment]
@kaaass 刚刚试了1.0.7的版本，VPN权限申请是正常了。不过我反馈的那个问题依旧存在。就是不显示连接配置信息

**Comment by brdctrai** [comment]
经过测试可以正常连接，问题可以关闭，谢谢！

**Comment by kaaass** [comment]
@xzl0326 感谢测试！不过这个问题需要重写 VPN 状态与 UI 的通信逻辑，修复起来需要一些时间，我之后再找时间看看。

**Comment by kaaass** [comment]
@brdctrai 好的，感谢测试！
