### ISSUE TITLE
安卓4.4没办法安装

### ISSUE THREAD

**Issue by DarkiT** [kaaass/ZerotierFix#5]
安卓4.4没办法安装，请问有没有安卓4.4的版本？

**Comment by kaaass** [comment]
目前最低支持 5.0，我稍后看看 4.4 兼容会不会有什么问题（应该没多少），没问题的话下个版本更新会支持 4.4

**Comment by DarkiT** [comment]
嗯，感谢你的付出，不知道能否修改成自动保存上一次的连接节点记录，然后加入开机启动的选项，这样只要安卓一开机就自动连接相应勾选的网络节点。

**Comment by DarkiT** [comment]
大佬能不能帮忙交叉编译一个Zerotier的二进制安卓版本文件，就像Linux版本那样的，全命令操作的那种，我想放在后台运行，自己倒腾了几天还是没搞定。

**Comment by kaaass** [comment]
不建议这么做。Zerotier Linux 版本会创建 tun 设备，因此需要 root 权限才可以。而且可能会与 Android 本身的网络管理冲突。

**Comment by DarkiT** [comment]
安卓设备已经拥有root权限了，我是安装在4G随身wifi里面的，所以想自启动，不知道能否帮忙编译一个，或者给个安卓的交叉编译教程也行。

**Comment by kaaass** [comment]
真有需求的话，可以使用 Android NDK 编译

**Comment by DarkiT** [comment]
ndk编译出来的是库文件，编译二进制一直失败。

**Comment by kaaass** [comment]
相关功能已经在 1.0.5_189 版本中实现
