### ISSUE TITLE
Zerotier Fix_1.0.7_011006_alpha ipv6 ping不了

### ISSUE THREAD

**Issue by openwrt2223** [kaaass/ZerotierFix#51]
Zerotier Fix_1.0.7_011006_alpha ipv6 ping不了。 @kaaass

**Comment by kaaass** [comment]
我这边暂时无法复现这个问题。可否提供更详细的测试步骤？

**Comment by openwrt2223** [comment]
> 我这边暂时无法复现这个问题。可否提供更详细的测试步骤？

用ZeroTier One_1.10.6-2加入 f57a6834044f619e 网络 打开 test-ipv6.com有ipv6地址，用Zerotier Fix_1.0.7_011006_alpha加入 f57a6834044f619e网络 打开test-ipv6.com没有ipv6地址。

**Comment by openwrt2223** [comment]
> 我这边暂时无法复现这个问题。可否提供更详细的测试步骤？

实际上是Zerotier Fix_1.0.7_011006_alpha的ipv6问题，我在1.0.5上没有发现这个问题，应该是1.0.6引入的bug

**Comment by kaaass** [comment]
> 打开 test-ipv6.com 有 ipv6 地址

test-ipv6 网站检查的是公网 IPv6 地址，而 Zerotier 正常情况下分配的是私有 IPv6 地址，无法通过这类测试网站检查。这类测试网站检查的应该是你当前的网络环境是否支持 IPv6（比如宽带是否支持 v6）。

**Comment by openwrt2223** [comment]
> > 打开 test-ipv6.com 有 ipv6 地址
> 
> test-ipv6 网站检查的是公网 IPv6 地址，而 Zerotier 正常情况下分配的是私有 IPv6 地址，无法通过这类测试网站检查。这类测试网站检查的应该是你当前的网络环境是否支持 IPv6（比如宽带是否支持 v6）。

我已经给f57a6834044f619e网络分配了公网ipv6地址并配置了路由。

**Comment by openwrt2223** [comment]
> > 打开 test-ipv6.com 有 ipv6 地址
> 
> test-ipv6 网站检查的是公网 IPv6 地址，而 Zerotier 正常情况下分配的是私有 IPv6 地址，无法通过这类测试网站检查。这类测试网站检查的应该是你当前的网络环境是否支持 IPv6（比如宽带是否支持 v6）。

![Screenshot_20230706-131307](https://github.com/kaaass/ZerotierFix/assets/92192602/7394e05c-40ed-4c33-919b-6dcea8825db3)
这是用ZeroTier One_1.10.6-2后的测试图。

**Comment by openwrt2223** [comment]
> > 打开 test-ipv6.com 有 ipv6 地址
> 
> test-ipv6 网站检查的是公网 IPv6 地址，而 Zerotier 正常情况下分配的是私有 IPv6 地址，无法通过这类测试网站检查。这类测试网站检查的应该是你当前的网络环境是否支持 IPv6（比如宽带是否支持 v6）。

![Screenshot_20230706-131307](https://github.com/kaaass/ZerotierFix/assets/92192602/38e97f20-7e7a-42a2-8194-7f308db7b561)

**Comment by kaaass** [comment]
> 我已经给 f57***** 网络分配了公网ipv6地址并配置了路由。

好的，感谢报告。我之后测试下这种情况。

P.S. 请谨慎分享网络 ID，若被滥用则可能引起一些不必要的麻烦

**Comment by kaaass** [comment]
本 Issue 的问题已经在 1.0.8_011006_alpha 版本中得到修复，请注意更新。若测试仍有问题，欢迎在此 Issue 下回复。

**Comment by openwrt2223** [comment]
> 本 Issue 的问题已经在 1.0.8_011006_alpha 版本中得到修复，请注意更新。若测试仍有问题，欢迎在此 Issue 下回复。

问题然而存在。
![Screenshot_2023-07-10-01-49-26-438_com termux](https://github.com/kaaass/ZerotierFix/assets/92192602/317088f1-30e4-4ba0-ade1-8273d9debbed)

**Comment by kaaass** [comment]
@openwrt2223 根据你的截图，ipv6 ping 的运行结果是正常的

**Comment by openwrt2223** [comment]
正常的是ZeroTier One_1.10.6-2

于 2023年7月10日 UTC 上午1:07:59, KAAAsS ***@***.***> 写到:

**Comment by openwrt2223** [comment]
正常的是用ZeroTier One_1.10.6-2 ping的。

于 2023年7月10日 UTC 上午1:07:59, KAAAsS ***@***.***> 写到:

**Comment by openwrt2223** [comment]
> @openwrt2223 根据你的截图，ipv6 ping 的运行结果是正常的

倒数第二条才是用Zerotier Fix_1.0.8_011006_alpha ping的。

**Comment by kaaass** [comment]
@openwrt2223 反馈时请尽可能清楚的说明你的问题和你做过的测试，以便于我这边复现问题后修复。

目前你遇到的 ping 问题是单向的还是双向的？图中 termux 的话是 “手机 -> 其他节点“，那 “其他节点 -> 手机“ 是否可以 ping 通？

**Comment by openwrt2223** [comment]
> @openwrt2223 反馈时请尽可能清楚的说明你的问题和你做过的测试，以便于我这边复现问题后修复。
> 
> 目前你遇到的 ping 问题是单向的还是双向的？图中 termux 的话是 “手机 -> 其他节点“，那 “其他节点 -> 手机“ 是否可以 ping 通？

第一次
手机>其它节点 不通
其它节点>手机 通
第二次
手机>其它节点 通
其它节点>手机 通
也就是其它节点先ping手机，手机才能ping其他节点。

**Comment by openwrt2223** [comment]
> @openwrt2223 反馈时请尽可能清楚的说明你的问题和你做过的测试，以便于我这边复现问题后修复。
> 
> 目前你遇到的 ping 问题是单向的还是双向的？图中 termux 的话是 “手机 -> 其他节点“，那 “其他节点 -> 手机“ 是否可以 ping 通？

在ZeroTier One_1.10.6-2和1.0.5上就没有问题。

**Comment by kaaass** [comment]
@openwrt2223 感谢测试！初步判断应该是和近期 NDP 相关的代码变更有关，具体我还需要再看看。

**Comment by kaaass** [comment]
@openwrt2223 需要对方先 Ping 的问题应该已经修复了，有空的话可以试一下这个版本。
[app-debug.zip](https://github.com/kaaass/ZerotierFix/files/11998503/app-debug.zip)

**Comment by openwrt2223** [comment]
> @openwrt2223 需要对方先 Ping 的问题应该已经修复了，有空的话可以试一下这个版本。 [app-debug.zip](https://github.com/kaaass/ZerotierFix/files/11998503/app-debug.zip)

这个版本没有问题。

**Comment by kaaass** [comment]
好的，感谢测试。预计在下个版本包含此修复。
