### ISSUE TITLE
ZerotierFix在Android 12+上的一些问题

### ISSUE THREAD

**Issue by openwrt2223** [kaaass/ZerotierFix#57]
ZerotierFix在Android 12+上的一些问题。
比如在android 11有弹窗提醒已连接而android 12确没有弹窗提醒已连接。

**Comment by kaaass** [comment]
这个 ”弹窗“ 指的是通知栏的常驻通知吗？还是会出现一瞬间的 Toast 气泡提示？

**Comment by openwrt2223** [comment]
> 这个 ”弹窗“ 指的是通知栏的常驻通知吗？还是会出现一瞬间的 Toast 气泡提示？

Toast提醒

**Comment by openwrt2223** [comment]
> 这个 ”弹窗“ 指的是通知栏的常驻通知吗？还是会出现一瞬间的 Toast 气泡提示？

常驻通知好像也有问题

**Comment by kaaass** [comment]
能否提供下具体的 ROM？ 我在模拟器环境下测试官方的 Android 13 似乎没有异常，也许和厂商修改有关。

**Comment by openwrt2223** [comment]
> 能否提供下具体的 ROM？ 我在模拟器环境下测试官方的 Android 13 似乎没有异常，也许和厂商修改有关。

小米miui

**Comment by kaaass** [comment]
好的，感谢报告。我找台机子测试下。

**Comment by kaaass** [comment]
找了台 MIUI 14.0.4 可以复现，感谢报告！

**Comment by kaaass** [comment]
此 BUG 已得到修复，预计将包含在 1.0.10 版本中。此外也可以从 Actions 中下载 Nightly Build 以抢先使用。
