### ISSUE TITLE
服务器地址是否支持使用域名

### ISSUE THREAD

**Issue by SinAngle** [kaaass/ZerotierFix#58]
[版本1.0.9]在添加服务器地址使用ip的自定义Planet时，网络是可以正常连接工作的，但是更改为服务器地址使用域名（例如xxx.f3322.net）的Planet时，会出现无法连接到网络的情况，无法获取网络名称，状态显示为‘正在请求配置’，但是pc端网络依旧正常连接，是否是Android端目前不支持使用域名，还是我操作错误，如果是不支持的话目前是否有替代方案，因为目前使用的服务器每隔一段时间会变更ip，然后服务器使用的是xubiaolin/docker-zerotier-planet，如果设置为固定ip需要经常重置非常麻烦

**Comment by kaaass** [comment]
Zerotier 本身的 Moon 和 Planet 是不支持 DDNS 的，且官方也多次表态过没有计划支持（zerotier/ZeroTierOne#881, zerotier/ZeroTierOne#918, zerotier/ZeroTierOne#1047, zerotier/ZeroTierOne#1158, zerotier/ZeroTierOne#2036）。因此 Zerotier Fix 作为一个下游软件也是不支持 DDNS 的。

不过 DDNS 在某些场景下的确是最经济的选择，因此 Zerotier Fix 并不排斥在之后的版本中提供支持，只是具体用什么形式支持还是需要斟酌的。使用 FQDN 作为节点地址的最大问题其实是在运行时域名解析的 IP 地址可能会发生变更，因此需要持续对 FQDN 进行解析，发生变更时有需要重新建立连接。从仓库维护的角度讲，我倾向于出现一个可以同时适用于多端的方案后再在 Zerotier Fix 上实现支持。
