### ISSUE TITLE
目标节点没有和手机成功建立 p2p 连接，节点列表中延迟为-1ms，通信路径为中继

### ISSUE THREAD

**Issue by captainbanana233** [kaaass/ZerotierFix#59]
系统版本为安卓13、MIUI14.0.9
moon节点与其他linux的设备和windows的设备都可以建立正常连接
在planet导入过程中，我是从配置为moon节点的服务端中下载的planet文件，并通过本地导入文件的方式导入，过程中没有出现错误提示
服务端为华为云搭建的服务器
在移动的流量下会出现这样的问题，但是在实验室WIFI中也会出现这样的问题，而在同样WIFI下的pc则能正常p2p连接moon节点

**Comment by captainbanana233** [comment]
刚刚又通过多次测试，目前情况如下：在WIFI环境下，偶尔不可以正常建立p2p连接，但是在建立了p2p连接后ping的波动较为明显且稍高（50-100ms，偶尔上200ms），不像pc上ping的延迟那么低，不知道是否为正常现象。而在移动和电信流量的环境下，基本不能建立p2p连接，感觉这可能跟网络环境有着更大的联系，

**Comment by kaaass** [comment]
> 在WIFI环境下，偶尔不可以正常建立p2p连接，但是在建立了p2p连接后ping的波动较为明显且稍高（50-100ms，偶尔上200ms），不像pc上ping的延迟那么低，不知道是否为正常现象

是正常现象。WIFI 通信本身就会引入 ping 波动，可以尝试直接 ping 同 WIFI 下的 pc，应该也有类似的波动。

> 而在移动和电信流量的环境下，基本不能建立p2p连接，感觉这可能跟网络环境有着更大的联系

你的分析很对。移动的 4/5G 很多情况下都是 Symmetric NAT，本身连通性就很差很难打洞。

**Comment by captainbanana233** [comment]
大概明白是怎么一回事了，谢谢大佬回复
