### ISSUE TITLE
是否可以提供转换为计费网络功能？

### ISSUE THREAD

**Issue by ZGLinus** [kaaass/ZerotierFix#61]
在使用移动网络时，开启zerotier fix后，有的应用无法读取正确的网络状态。如果把网络连接改为计费网络 `metered network`，就可以让这部分应用读取到自己在移动网络环境。
可以在设置界面加入开关，让用户自行决定改为计费网络。

相关链接：https://developer.android.google.cn/reference/kotlin/android/net/VpnService.Builder#setmetered

**Comment by kaaass** [comment]
我看了眼文档，`setMetered` 的行为似乎是 ”强制设置当前为计费网络“。

> Otherwise, set this to false. Doing so would cause VPN network to inherit its meteredness from its underlying networks.

从这段内容来看使用默认值 `false` 时这个配置同样也会根据底层的网络类型来判断 VPN 网络是否是计费的。而且在 Android 10 及以上的版本已经默认设置为 `true` 了。按照文档的意思，你遇到的问题可能不一定与 `setMetered` 有关。

**Comment by ZGLinus** [comment]
好吧
