### ISSUE TITLE
自动更新moon/planet, 以适应动态ip

### ISSUE THREAD

**Issue by basncy** [kaaass/ZerotierFix#68]
moon/planet服务器上有个脚本, 每次IP更新后自动生成新的moon/planet文件. Linux/Win 已使用syncthing同步更新此文件.

android上首次导入moon和planet后不会自动更新, 希望增加此功能. 每次启动的时候从url下载最新的.

**Comment by kaaass** [comment]
听起来可以实现类似 DDNS 的效果，好棒！我考虑在之后的版本试验性的添加下，不过优先级可能不会那么高所以短期可能不会做，可以持续关注下本 Issue

**Comment by basncy** [comment]
如果仅自建moon, 给个选项每次启动时自动刷新moon缓存也能达到同样效果.

**Comment by kaaass** [comment]
@basncy 目前通过 URL 下载 Moon 文件的时候不会存 URL，所以做的话应该和 Planet 也差不多

**Comment by basncy** [comment]
可以通过moon地址更新, 遍历moons.d文件夹就行了.
或者启动时先清空moons.d里的缓存,让zerotier自己去更新(未验证)

**Comment by kaaass** [comment]
通过地址更新需要删除缓存的 Moon 文件并在网络启动的时候 orbit。如果只配置了一个 Moon 并且 Planet 的连通性不好的话其实应该也不太能顺利更新的。这个需求应该还是要 URL 下载才能实现。

**Comment by basncy** [comment]
这里要解决的是通过更新moon缓存搞定带宽和延时问题.

对于planet连通性, 极端网络条件下, 可以临时用手机流量更新一下.(比较灵活的选项是让用户选择:是否在每次启动时自动更新缓存)

通过URL下载能从根本上解决问题, 但需要的配套设施和维护也挺多的.

**Comment by basncy** [comment]
找҃到一种更好҄的方案: https://github.com/kaaass/ZerotierFix/issues/82

**Comment by wongsyrone** [comment]
https://github.com/kaaass/ZerotierFix/issues/113
