### ISSUE TITLE
旧设备断开网络后无法再次连接 / Cannot reconnect to network after disconnect in old device

### ISSUE THREAD

**Issue by signigelchan** [kaaass/ZerotierFix#74]
## 问题简述
1. 按钮开启，成功授权组网后，按钮关闭，无法重置状态，导致后续不能重新开启功能，除非强制杀掉App。(状态未重置)
2. Android 4.4.2 组网后，不能访问组网设备。(成功组网，但不能访问)
---
## 测试机型
- 手机 OPPO R9s (Android 6.0.1)
- 车机 (Android 4.4.2)
---
## 网络环境
- 手机流量，开启WiFi热点。
---
## 机型详情
![手机](https://github.com/kaaass/ZerotierFix/assets/20301894/d0829438-db77-4386-b8c5-0b7d8e6a0095)
---
![车机](https://github.com/kaaass/ZerotierFix/assets/20301894/bdb4b802-63a8-4763-9dec-0839f8da6ce1)
---
## 手机测试截图
![手机组网01](https://github.com/kaaass/ZerotierFix/assets/20301894/2c82314c-54f4-459e-9f49-6b0ac5a3e39d)
![手机组网02](https://github.com/kaaass/ZerotierFix/assets/20301894/cab0677b-3b30-4de6-8a1b-74f51c5b26a4)
![手机组网03](https://github.com/kaaass/ZerotierFix/assets/20301894/580bb9f0-e2ef-4e92-bafb-0f99147cc4c2)
---
## 车机测试截图
![ 车机组网01](https://github.com/kaaass/ZerotierFix/assets/20301894/a8c57fe4-2c24-4ae3-8c11-d287b830ffa4)
---

**Comment by U11Leung** [comment]
我这边有一个来自 https://www.urovo.com/ 的设备，智能数据终端，运行android 9.0，有和这个一模一样的问题，可以注册和第一次连接vpn，之后的断开要从系统层面断开而不能用单用软件里的断开；不过，没什么机会提供log文件之类的

**Comment by kaaass** [comment]
感谢详细的报告！看起来可能是旧版本系统中 VPN Service 的管理有 BUG。不过我目前手头没有 6.0.1 和 4.4.2 的设备，4.4.2 官方的模拟器好像暂时没测出类似的问题。我会尽量找旧设备实机测试下。

此外，下个版本我会考虑加入保存诊断日志的功能，希望对修复此问题有帮助。

**Comment by kaaass** [comment]
刚刚用一台 5.1 的机器成功复现了这个问题，大致定位到了问题原因。各位如果方便的话可以测试下问题是否得到了修复～
[app-debug.apk.zip](https://github.com/kaaass/ZerotierFix/files/14210176/app-debug.apk.zip)

**Comment by U11Leung** [comment]
反馈一下，有效果，我的设备更新后问题不存在了，可以随意正常连接断开，感谢作者，在继续试用中

**Comment by kaaass** [comment]
@U11Leung 感谢报告！目前看起来这个问题已经修复了，本 Issue 将关闭。如果还有测试结果或者问题仍旧存在的报告欢迎继续回复。
