### ISSUE TITLE
手机添加自建的planet时，提示“planet文件格式错误”

### ISSUE THREAD

**Issue by joshddd** [kaaass/ZerotierFix#75]
一部三星手机一部vivo手机，不管是把moon文件下载到手机存储添加，还是通过url添加，都显示同样的问题，三星手机卸载重装最新版本后可以使用了，vivo手机重装还是解决不了。

**Comment by kaaass** [comment]
麻烦提供下手机 ROM 及 Android 的版本

**Comment by joshddd** [comment]
对不起，自己犯了低级错误，请忽略>_<

**Comment by kaaass** [comment]
没事 ：）
