### ISSUE TITLE
增加只走moon节点连接功能

### ISSUE THREAD

**Issue by Vant1032** [kaaass/ZerotierFix#76]
我自建了moon节点，服务器在美国， 添加了moon节点，但是在5G网络下依然极其慢，处于无法使用的状态，我怀疑是走了zerotier官方服务器，因为我本身美国服务器线路是cn2的网络很好，不应该这么慢。

如果能增加只走moon节点中转功能会更好

**Comment by Vant1032** [comment]
貌似是我的美国moon节点被防火墙干扰了，可能moon节点得搭在国内会好一点

**Comment by kaaass** [comment]
> 我自建了moon节点，服务器在美国， 添加了moon节点，但是在5G网络下依然极其慢，处于无法使用的状态，我怀疑是走了zerotier官方服务器

Moon 节点如果跨国的话，在部分网络条件下 P2P 打洞的结果可能是会比较慢的，建议是把 Moon 尽量放的近一点。可以通过主界面右上角功能菜单里面的 “节点列表” 来检查你和目标设备的连接方式，看看是否是有打洞，还是说已经显示是中继了。

> 如果能增加只走moon节点中转功能会更好

这个 Zerotier Fix 本身没法实现，因为暂时还是不打算对 Zerotier 本身做代码修改，可以考虑给官方 [zerotier/ZerotierOne](https://github.com/zerotier/ZeroTierOne) 提一个 Issue。
