### ISSUE TITLE
moon端口改了

### ISSUE THREAD

**Issue by verabq** [kaaass/ZerotierFix#8]
大佬moon服务器的端口改成其他的这个客户端是不是就连不上了？
之前默认9993可以连上看到延迟
自定义端口后延迟就一直-1
我电脑的客户端连的都正常。。。

**Comment by kaaass** [comment]
请检查一下是否开放了新端口的 udp

**Comment by verabq** [comment]
是我的问题，好像端口还是没改成功
服务器重开放9993后就好了

奇怪了服务器moon.json配置的时候明明改成其他端口了
"stableEndpoints": [ "23.23.23.23/9993" ]难道不是这里改吗？难受啊.

**Comment by kaaass** [comment]
> 奇怪了服务器moon.json配置的时候明明改成其他端口了 "stableEndpoints": [ "23.23.23.23/9993" ]难道不是这里改吗？难受啊.

改端口的话还需要重新生成相关文件。JSON 文件其实不影响程序运行。
