### ISSUE TITLE
直连网速跑不满

### ISSUE THREAD

**Issue by xq-yu** [kaaass/ZerotierFix#83]
自建私有planet，同样的网络环境，手机端zerotierfix直连服务器传输文件网速跑不满，测试情况如下
1. 手机服务器均在用一个WiFi下，通过zerotier直连网络传输，网速无法跑满（5Mb/s左右）；直接走wifi内网ip传输可以跑满
2. 测试了多种传输协议均存在这种情况，但是pc客户端zerotier没有问题

**Comment by kaaass** [comment]
Zerotier 协议 + 实现本身就有速度上线，和具体设备的算力有一定关系。根据 [netmaker](https://medium.com/netmaker/battle-of-the-vpns-which-one-is-fastest-speed-test-21ddc9cd50db) 的测试，Zt 大致的带宽是 56.8 Mbps，约为 7.1 MB/s。手机性能差一点而且 APP 多了一层 Java，理论上会更慢一些，你的速度应该属于正常范围。

**Comment by wongsyrone** [comment]
可以试试去掉一部分copy之后有没有变化，https://github.com/kaaass/ZerotierFix/issues/96#issuecomment-2658433106
